"""empty message

Revision ID: 7e3b90438f90
Revises: 8adfeecb7649
Create Date: 2021-02-25 15:08:02.204096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e3b90438f90'
down_revision = '8adfeecb7649'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buttons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('chapters_story_id_fkey', 'chapters', type_='foreignkey')
    op.create_foreign_key(None, 'chapters', 'stories', ['story_id'], ['id'])
    op.add_column('messages', sa.Column('from_button_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'messages', 'buttons', ['from_button_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'from_button_id')
    op.drop_constraint(None, 'chapters', type_='foreignkey')
    op.create_foreign_key('chapters_story_id_fkey', 'chapters', 'stories', ['story_id'], ['id'], ondelete='CASCADE')
    op.drop_table('buttons')
    # ### end Alembic commands ###
