"""empty message

Revision ID: b7f055a0711d
Revises: 14fd960771be
Create Date: 2021-02-21 19:34:52.927939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7f055a0711d'
down_revision = '14fd960771be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('name', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'stories', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stories', type_='unique')
    op.drop_column('stories', 'name')
    # ### end Alembic commands ###
