"""empty message

Revision ID: 03c96d0181c4
Revises: 3fb43b9994b1
Create Date: 2021-06-23 09:46:06.436583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03c96d0181c4'
down_revision = '3fb43b9994b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('link_id', sa.Integer(), nullable=True))
    op.drop_constraint('messages_parent_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'messages', ['link_id'], ['id'])
    op.drop_column('messages', 'parent_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_parent_id_fkey', 'messages', 'messages', ['parent_id'], ['id'])
    op.drop_column('messages', 'link_id')
    # ### end Alembic commands ###
