"""empty message

Revision ID: 3fb43b9994b1
Revises: f003d42a1863
Create Date: 2021-06-06 12:33:50.259992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fb43b9994b1'
down_revision = 'f003d42a1863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wait_reactions', sa.Column('uid', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wait_reactions', 'uid')
    # ### end Alembic commands ###
