"""empty message

Revision ID: 50d19a7ccd93
Revises: 5fbc01023020
Create Date: 2021-06-05 20:15:37.378351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50d19a7ccd93'
down_revision = '5fbc01023020'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
