"""empty message

Revision ID: 5fbc01023020
Revises: be213c907efa
Create Date: 2021-06-03 14:19:42.942625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fbc01023020'
down_revision = 'be213c907efa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('referal_block', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'referal_block')
    # ### end Alembic commands ###
