"""empty message

Revision ID: 861642d09a64
Revises: 8f6515da031d
Create Date: 2021-05-31 17:08:00.192305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '861642d09a64'
down_revision = '8f6515da031d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('timeout', sa.Integer(), nullable=True))
    op.add_column('stories', sa.Column('base_timeout', sa.Integer(), nullable=True))
    op.add_column('stories', sa.Column('k_timeout', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'k_timeout')
    op.drop_column('stories', 'base_timeout')
    op.drop_column('messages', 'timeout')
    # ### end Alembic commands ###
