"""empty message

Revision ID: 8f6515da031d
Revises: 9d8ed1656506
Create Date: 2021-05-30 19:24:28.691941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f6515da031d'
down_revision = '9d8ed1656506'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buttons', sa.Column('number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buttons', 'number')
    # ### end Alembic commands ###
