"""empty message

Revision ID: be213c907efa
Revises: 861642d09a64
Create Date: 2021-06-02 16:36:17.183849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be213c907efa'
down_revision = '861642d09a64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wait_reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('wait_reaction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['wait_reaction_id'], ['wait_reactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('messages', sa.Column('wait_reaction_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'messages', 'wait_reactions', ['wait_reaction_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'wait_reaction_id')
    op.drop_table('reactions')
    op.drop_table('wait_reactions')
    # ### end Alembic commands ###
