"""empty message

Revision ID: f003d42a1863
Revises: 50d19a7ccd93
Create Date: 2021-06-05 20:35:12.577426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f003d42a1863'
down_revision = '50d19a7ccd93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('uid', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'stories', ['uid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stories', type_='unique')
    op.drop_column('stories', 'uid')
    # ### end Alembic commands ###
